name: .NET WPF Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x' # или '7.0.x', если используется

      - name: Restore dependencies
        run: dotnet restore "Проект Экзамен/Travel-Company.WPF.sln"

      - name: Build solution
        run: dotnet build "Проект Экзамен/Travel-Company.WPF.sln" --configuration Release

      - name: Publish build artifacts
        run: dotnet publish "Проект Экзамен/Travel-Company.WPF.sln" -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WPF-App
          path: ./publish
